name: ninja_hijau
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  bonfire: ^3.15.1
  flame_audio: ^2.10.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/audio/effects/
    - assets/images/
    - assets/images/effects/
    - assets/images/items/
    - assets/images/sprite_sheets/
    - assets/images/decorations/
